#!/bin/bash
if [ "$(/usr/bin/biber --version)" = "biber version: 2.17" ]; then
    TEXMFLOCAL=/usr/local/share/texmf
    echo adding patched apa.bbx into $TEXMFLOCAL, to work with biber 2.17
    mkdir -p ${TEXMFLOCAL}/tex/latex/
    cp -r /usr/share/texlive/texmf-dist/tex/latex/biblatex-apa ${TEXMFLOCAL}/tex/latex/
    perl -p -e 's/usenarrator=true/} % usenarrator=true/' /usr/share/texlive/texmf-dist/tex/latex/biblatex-apa/apa.bbx > ${TEXMFLOCAL}/tex/latex/biblatex-apa/apa.bbx
fi
texhash
